name: Continuous Delivery

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  continuous-integration:
    name: Continuous integration
    runs-on: ubuntu-latest

    steps:
      - name: Download code from GitHub
        uses: actions/checkout@v4.1.1

      - name: Install pnpm package manager
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.14

      - name: Set up Node.js version
        uses: actions/setup-node@v4.0.1
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies specified in package.json
        run: |
          pnpm install
          pnpm ls

      - name: Run the lint script in package.json scripts
        run: |
          pnpm run lint

      - name: Run the build script in package.json scripts
        run: |
          pnpm run build

      - name: Run the test script in package.json scripts
        run: |
          pnpm run test

      - name:
        uses: actions/upload-artifact@v4.2.0
        with:
          name: build
          path: .next/
          retention-days: 42
